import tsParser from "@typescript-eslint/parser";
import jsdoc from "eslint-plugin-jsdoc";

// This configuration owns commentary and nothing else, matching the shape the
// application uses. Biome owns style and correctness for this project too, so
// a rule that both could report is a finding delivered twice and is
// deliberately absent here.
//
// It reads `steps/` rather than `src/`: this project's source is its step
// definitions, and `.features-gen/` beside them is generated by `bddgen` on
// every run, so holding generated code to a commentary standard would report
// findings nobody can fix.
export default [
  {
    files: ["steps/**/*.ts"],
    // ESLint's own parser reads JavaScript only, so it stops at the first type
    // annotation and reports a parse error instead of a commentary finding.
    // The TypeScript parser is loaded for its reader alone: no
    // `@typescript-eslint` rule is enabled here, because every rule that plugin
    // offers is one Biome already reports for this project. No `jsx` feature is
    // enabled, unlike the application's configuration — a Playwright step file
    // never contains JSX.
    languageOptions: {
      parser: tsParser,
    },
    plugins: { jsdoc },
    rules: {
      // A named executable declaration is one a future reader will look up by
      // name, so it owes them a sentence saying what it is for. Anonymous and
      // inline functions are excluded: naming a callback's purpose belongs in
      // the call site that reads it, not in a comment above it. That exclusion
      // is what keeps every `Given`/`When`/`Then` arrow in a step file out of
      // scope, which is right — a step's meaning is the Gherkin line it binds.
      "jsdoc/require-jsdoc": [
        "error",
        {
          require: {
            FunctionDeclaration: true,
            ClassDeclaration: true,
            MethodDefinition: true,
            ArrowFunctionExpression: false,
            FunctionExpression: false,
          },
        },
      ],
      // A summary that is not a sentence is a label, and a label repeats the
      // name rather than explaining it.
      "jsdoc/require-description": ["error", { descriptionStyle: "body" }],
      // The rule ends a sentence at every period, so an abbreviation reads as a
      // full stop and whatever follows it reads as a sentence starting in
      // lowercase. Listing the abbreviations this codebase actually writes
      // keeps the rule reporting real findings instead of punctuation it
      // misread.
      "jsdoc/require-description-complete-sentence": [
        "error",
        { abbreviations: ["e.g", "i.e", "etc", "vs"] },
      ],
    },
  },
];
